**Problem 1**

Consider the following dataset:
`Dataset = ([1, 2, 5, 6]), Targets = ([-1,-1,1,1])`

Apply the least squares classifier to obtain the corresponding decision boundary if p = 6.


In [3]:
import numpy as np

In [7]:
x = np.array([1, 2, 5, 6])
x_tilda = np.concatenate((x.reshape(4,1), np.ones((4,1))), axis=1) # ~~> converting X into ~X (X tilda)
# NB: axis=0 means concatenating rows, axis=1 means concatenating columns (default is 0)
targets = np.array([-1,-1,1,1]).reshape(4,1)

In [5]:
w = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targets
print(w)
# first element is w1 and second is w0 (w node)

[[ 0.47058824]
 [-1.64705882]]


Apply the least squares classifier to obtain the corresponding decision boundary if p = 20.

In [9]:
x = np.array([1, 2, 5, 20])
x_tilda = np.concatenate((x.reshape(4,1), np.ones((4,1))), axis=1) 
targets = np.array([-1,-1,1,1]).reshape(4,1)

array([ 1,  2,  5, 20])

In [10]:
w = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targets
print(w)

[[ 0.47058824]
 [-1.64705882]]


**Problem 2**

Consider the two-dimensional dataset below: `Dataset: ([[1,1],[5,-5],[-1,-1],[-5,5]]), Targets = ([1,-1,1,-1])`
Apply the least squares classifier to obtain the corresponding decision boundary. Comment on the outcome. What could you do to make this classifier work on this dataset?

---



In [15]:
x2 = np.array([[1,1],[5,-5],[-1,-1],[-5,5]])
x2_tilda = np.concatenate((x2, np.ones((4,1))), axis=1) 
targets2 = np.array([1,-1,1,-1]).reshape(4,1)


In [16]:
w2 = np.linalg.inv(x2_tilda.T @ x2_tilda) @ x2_tilda.T @ targets2
print(w2)

[[0.]
 [0.]
 [0.]]


Result of zero means that there exists no solution to this problem. 
- The least squares classifier is a linear classifier, therefore it failed in classifying a non-linearly separable dataset. 
- To make the least squares classifier work on this dataset, we can apply nonlinear transformation on the data. 
- Nonlinear transformation will transform the data from nonlinearly separable data to linearly separable data which could be classified using the least squares classifier.
- One of the possible nonlinear transformation functions that could be applied to the data above is the norm/magnitude (the distance between each point and the origin).

There are two options for the failure of the classifier. 
1. The first one is that the classifier does not find a decision boundary (zero weight vector) like the above example. 
2. The second one is that the classifier finds a wrong (or inaccurate) decision boundary.
